### ISSUE TITLE
InfoについてのColor指定もあるのが望ましい

### ISSUE THREAD

**Issue by minmin0530** [digital-go-jp/design-system-example-components#10]
## issue の番号

> #[10]
## Issueの内容

> InfoについてのColor指定もあるのが望ましい。
## どんな追加・修正をしたのか

> 例えば、灰色（Gray）系統の色 #949494 でInfoのColor指定を書いておくなどの修正を希望。
下記リンクなどで使われているInfo系のカラー
[カラーについての表記](https://design.digital.go.jp/foundations/color/)
![InfoColor](https://github.com/digital-go-jp/design-system-example-components/assets/599842/bf5c817d-10ca-445c-9687-bd60484039ed)

## 動作検証方法

- [ ] 開発環境での実行
- [ ] 本番環境での実行
- [ ] テスト実行
- [ ] その他

> 該当するものにチェック
### 備考
[tokens-color--example](https://github.com/digital-go-jp/design-system-example-components/blob/main/src/tokens/Colors.tsx)

**Comment by johnykei** [comment]
@minmin0530 様

Issueの作成ありがとうございます。

当リポジトリではまずはコンポーネントそのものに関してのIssueを受け付けたいと考えております。

先程READMEの更新をし、方針について記載しましたので、大変申し訳ございませんが改めて内容をご確認の上、
お気づきの点やご要望がございましたらご連絡ください。

何卒よろしくお願いいたします。

**Comment by johnykei** [comment]
上記のコメントの通り、申し訳ございませんがクローズさせていただきます。
ありがとうございました。
