### ISSUE TITLE
GoodFirstIssueをLabelsに用意しておくのが望ましい

### ISSUE THREAD

**Issue by minmin0530** [digital-go-jp/design-system-example-components#11]
## issue の番号

> #[11]
## Issueの内容

> 簡単なIssueは初心者コントリビューターのために残しておいて、GoodFirstIssueラベルを付けておくのが望ましい。
## どんな追加・修正をしたのか

> 修正した内容を記載

### 備考

**Comment by sacky3105** [comment]
あとは、EnhancementやTestなどの項目もLabelsに用意しておくと望ましいですよね。

**Comment by johnykei** [comment]
@minmin0530  様

Issueの作成ありがとうございます。

当リポジトリではまずはコンポーネントそのものに関してのIssueを受け付けたいと考えております。

先程READMEの更新をし、方針について記載しましたので、大変申し訳ございませんが改めて内容をご確認の上、
お気づきの点やご要望がございましたらご連絡ください。

何卒よろしくお願いいたします。

**Comment by johnykei** [comment]
上記のコメントの通り、申し訳ございませんがクローズさせていただきます。
ありがとうございました。
