### ISSUE TITLE
ci: change to Bun.js

### ISSUE THREAD

**Issue by EdamAme-x** [digital-go-jp/design-system-example-components#14]
5x ~ 25x faster
https://github.com/digital-go-jp/design-system-example-components/pull/13

**Comment by johnykei** [comment]
@EdamAme-x 様

IssueおよびPRの作成ありがとうございます。

当リポジトリではまずはコンポーネントそのものに関してのIssueを受け付けたいと考えております。

先程READMEの更新をし、方針について記載しましたので、大変申し訳ございませんが改めて内容をご確認の上、
お気づきの点やご要望がございましたらご連絡ください。

何卒よろしくお願いいたします。

**Comment by johnykei** [comment]
上記のコメントの通り、申し訳ございませんがクローズさせていただきます。
ありがとうございました。
