### ISSUE TITLE
ci: set paths which don't need ci of actions at paths-ignore

### ISSUE THREAD

**Issue by EdamAme-x** [digital-go-jp/design-system-example-components#16]
".vscode", ".github", etc.. は、ciを行う必要が有りません。

### 事例
https://github.com/honojs/hono/blob/main/.github/workflows/ci.yml

**Comment by johnykei** [comment]
@EdamAme-x 様

IssueおよびPRの作成ありがとうございます。

当リポジトリではまずはコンポーネントそのものに関してのIssueを受け付けたいと考えております。

先程READMEの更新をし、方針について記載しましたので、大変申し訳ございませんが改めて内容をご確認の上、
お気づきの点やご要望がございましたらご連絡ください。

何卒よろしくお願いいたします。

**Comment by EdamAme-x** [comment]
返信ありがとうございます。
私はこのIssueを閉じて、PullRequestに関して何を行えば良いでしょうか・・・？
お忙しいところ、申し訳ございません。

**Comment by johnykei** [comment]
@EdamAme-x 様

今回作成頂いたIssueおよびPullRequestに関してはこちら側でCloseさせていただきます。
こちらの準備不足ですぐに方針を出せず大変申し訳ございませんでした。いただいた内容は今後の開発の参考にさせていただきます。
改めて貴重なご意見を頂き誠にありがとうございました。

**Comment by johnykei** [comment]
上記のコメントの通り、申し訳ございませんがクローズさせていただきます。
ありがとうございました。
