### ISSUE TITLE
Storybook Input の例にテキストを入力できないものがある

### ISSUE THREAD

**Issue by ysds** [digital-go-jp/design-system-example-components#19]
Storybook の Input ページの上から 3 つ目の例に `value=""` が指定されているため、テキストを入力することができないようです。

<img width="745" alt="image" src="https://github.com/digital-go-jp/design-system-example-components/assets/4065765/35f1088e-f5a7-4e03-8e7c-111e72f47601">

https://github.com/digital-go-jp/design-system-example-components/blob/b124a9c8f036824121190b6f6c253af8b1591284/src/components/input/Input.stories.tsx#L51

もし、意図的なものであれば無視していただけばと思います。
Figma の 1.4.2 では「入力済の内容」と「誤った入力内容」が並んでおり、そもそもこの 3 つ目の例はなくても良いのかもしれません。

<img width="376" alt="image" src="https://github.com/digital-go-jp/design-system-example-components/assets/4065765/c3883203-3335-496b-93b1-3c268c1fc23e">

**Comment by ysds** [comment]
関連して、Textarea の例の中にエラーの例なのに "任意" が表示されているものを見つけました。意図的であればよいのですが、違和感がありました。「※必須」の方が自然かもしれません。

<img width="884" alt="image" src="https://github.com/digital-go-jp/design-system-example-components/assets/4065765/7e086485-cfa2-4fea-964f-c4ed7bfa3f94">

Input の例の見直しと合わせてこちらもご確認をご検討ください。

**Comment by johnykei** [comment]
@ysds 様

Issueの作成ありがとうございます。

タイトルの「Storybook Input の例にテキストを入力できないものがある」という点について、こちらは意図したものではなく不具合であることを確認いたしました。修正対応を進めてまいります。
また、このサンプルが必要かどうかについても再度チームで検討いたします。

さらに、コメントでいただいた「任意のTextareaでのエラー例」についても、サンプルとして正しくありませんので、こちらも修正対応を進めてまいります。

上記の対応が完了しましたら、再度こちらのIssueでお知らせいたします。

**Comment by johnykei** [comment]
@ysds 

こちらのIssueで報告いただいた以下の件について修正対応が完了いたしました。
お時間がある時にでもご確認いただけると幸いです。

- InputコンポーネントStorybookの、テキスト入力欄が空、かつエラー状態のサンプルで、テキストが入力できない問題を修正
- TextareaコンポーネントStorybookの、任意項目、かつエラー状態のサンプルを必須項目に変更

このIssueはこちらでクローズさせていただきます。もし、何か問題がありましたらまたコメントしてください。

改めて、ありがとうございました。
