### ISSUE TITLE
Legend の isDisabled 時の色が適用されていない

### ISSUE THREAD

**Issue by ysds** [digital-go-jp/design-system-example-components#20]
Legend に isDisabled を指定しても薄い色が適用されていません。

<img width="596" alt="image" src="https://github.com/digital-go-jp/design-system-example-components/assets/4065765/8989f303-9ea5-4806-bf5c-e5314cd67206">

Checkbox や Radio などの例にも影響があります。

<img width="207" alt="image" src="https://github.com/digital-go-jp/design-system-example-components/assets/4065765/cbd396d5-11a0-46e9-b7c7-b1ccfbe0c45f">

以下のように変更することで修正することができます。

```diff
  <legend
    className={`
-     flex w-fit items-center gap-2 text-dns-16B-2 text-solid-grey-900
-     ${isDisabled ? 'text-solid-grey-600' : ''}
+     flex w-fit items-center gap-2 text-dns-16B-2
+     ${isDisabled ? 'text-solid-grey-600' : 'text-solid-grey-900'}
```

**Comment by johnykei** [comment]
@ysds 様

不具合のご報告、ありがとうございます。

ご報告いただいた不具合がこちらでも再現されることを確認いたしました。
また、ご提案いただいた修正方法についても問題がないことを確認いたしました。

修正対応を進めてまいります。対応が完了しましたら、再度こちらのIssueでお知らせいたします。

**Comment by johnykei** [comment]
@ysds 

こちらのIssueで報告いただいた以下の件について修正対応が完了いたしました。
お時間がある時にでもご確認いただけると幸いです。

- Legend コンポーネントの isDisabled のカラースタイルが適用されていなかった問題を修正

このIssueはこちらでクローズさせていただきます。もし、何か問題がありましたらまたコメントしてください。

改めて、ありがとうございました。
