### ISSUE TITLE
A11y: ScrollToTopButtonコンポーネントのアクセシビリティ向上

### ISSUE THREAD

**Issue by BoxPistols** [digital-go-jp/design-system-example-components#21]
# Issue: ScrollToTopButtonコンポーネントのアクセシビリティ向上

## 該当コンポーネント

http://localhost:6006/?path=/story/component-scrolltotopbutton--example
<img width="700" alt="image" src="https://github.com/digital-go-jp/design-system-example-components/assets/10333049/ede46a70-49c6-4b16-bc40-c2c8460cfeb9">

## 背景

現在の `ScrollToTopButton` コンポーネントは `<a>` タグを使用していますが、セマンティック観点ではボタンの方が適切だと思います。
また、現状ではキーボードアクセシビリティの強化や明確なフォーカススタイルが欠け、スクリーンリーダーやその他の支援技術がコンポーネントを正しく解釈しない可能性があります。

### 提案内容

- コンポーネントを `<a>` タグから `<button>` タグに変更し、セマンティックな構造を改善
- スクリーンリーダーのサポートを向上させるためにARIA属性を改善
- キーボードアクセシビリティとフォーカススタイルを追加し、全ユーザーに対するユーザーエクスペリエンスを向上

#### Diff

```diff
-export type ScrollToTopButtonProps = ComponentProps<'a'>;
+export type ScrollToTopButtonProps = ComponentProps<'button'>;
 
export const ScrollToTopButton = (props: ScrollToTopButtonProps) => {
   const { className, ...rest } = props;
 
   return (
-    <a className={`${scrollToTopButtonStyle} ${className ?? ''}`} {...rest}>
+    <button
+      className={`${scrollToTopButtonStyle} ${className ?? ''}`}
+      aria-label={rest['aria-label'] ?? 'ページ上部に戻る'}
+      {...rest}
+    >
       <svg
-        aria-label={rest['aria-label'] ?? 'ページ上部に戻る'}
         fill='none'
         height='16'
         role='img'
         viewBox='0 0 15 16'
         width='15'
       >
         <path
           d='M6.75 15.5L6.75 3.37303L1.05383 9.06918L0 7.99998L7.49997 0.5L15 7.99998L13.9461 9.06918L8.24995 3.37303L8.24995 15.5H6.75Z'
           fill='currentColor'
         />
       </svg>
-    </a>
+    </button>
   );
 };
```

### 備考：
- `role='img'`ですが、画像としての意味合いがなくButton内の装飾だけの役割とすれば`role='presentation'`でも良さそうです
- このコンポーネントが常に単一の目的であれば`aria-label={rest['aria-label'] ?? 'ページ上部に戻る'}`→`aria-label="ページ上部に戻る"` または分岐なしの変数（多言語対応の想定で）`aria-label={scrollToTop}`などでも良いかと思います

## 提案まとめ

これらの変更により、以下の改善が期待されます：

- セマンティクスの向上: <button> タグを使用することで、スクリーンリーダーやその他の支援技術に対して正しい意味を提供します。
- アクセシビリティの強化: ARIA属性とフォーカススタイルにより、キーボードユーザーやスクリーンリーダーユーザーに対してボタンのアクセシビリティが向上します。
- 一貫したユーザーエクスペリエンス: フォーカススタイルにより、ボタンが視覚的なフィードバックを提供し、全体的なユーザーエクスペリエンスが向上します。

既存では不可であった、フォーカス時にキーボードSpaceボタンなどでインタラクション対応が可能となります

以上の対応で、このコンポーネントがアクセシビリティとユーザビリティの向上に貢献することが期待できます

また、Storybook側は以下のようなargsなどに差し替わる想定で考えています
```diff
export const Example: Story = {
  args: {
-    href: '#',
+   className: 'example',
  },
};
```

<img width="558" alt="image" src="https://github.com/digital-go-jp/design-system-example-components/assets/10333049/dc684732-b9a5-4351-a276-e54a92e9bd0a">

ご確認よろしくお願いいたします。

**Comment by johnykei** [comment]
@BoxPistols 様

Issueの作成ありがとうございます。

いただいたScrollToTopButtonコンポーネントのアクセシビリティ向上のためのご提案について、チームで確認いたしましたので、以下のとおり回答いたします。

まず前提として、「スクロールトップボタン」は [デジタル庁デザインシステムデザインデータ v2.0.0](https://www.figma.com/community/file/1377880368787735577) からは削除されています。
そのため、v1系にのみ存在するコンポーネントに関しては、チームで検討の上、重要なアクセシビリティに関する問題のみの対応となる可能性があることを予めご了承ください。

## マークアップについて

ご提案の通り、ScrollToTopButtonコンポーネントという名前やこのコンポーネントの挙動からすると、`button` 要素を使用するの適切ですので、button要素に変更のうえ、`aria-label` に入っているラベルを「ページの先頭へ戻る」にするという修正対応を進めてまいります。

## ボタンのラベルについて

アイコンだけのボタンのアイコン画像について、私たちは装飾ではなく意味のある画像として考えています。そのため、画像の代替テキストにラベルを入れる方針を取っています。
詳しくはデジタル庁デザインシステム専用サイトの「[ボタン（アクセシビリティ） - ラベルがアイコンだけのボタンに代替テキストを必ず指定する｜デジタル庁デザインシステム](https://design.digital.go.jp/components/button/?tab=accessibility#h3-%E3%83%A9%E3%83%99%E3%83%AB%E3%81%8C%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3%E3%81%A0%E3%81%91%E3%81%AE%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%AB%E4%BB%A3%E6%9B%BF%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%82%92%E5%BF%85%E3%81%9A%E6%8C%87%E5%AE%9A%E3%81%99%E3%82%8B)」に記載していますので、一読していただけると幸いです。

## aria-label の分岐について

想定する使用方法としてはページの先頭へ表示位置を移動させるものではありますが、このコンポーネントを用いて、現在位置よりは上にある任意の位置への移動させるトリガーとして使用するといった応用が考えられますので、必要に応じて開発者が変更できるような（あるいは変更できるという意図が伝わるような）記述を採用しております。そのため、こちらにつきましては現状の実装のままとさせて頂きます。

回答は以上となります。
`button` 要素への変更と `aria-label` のラベル修正対応が完了しましたら、再度こちらのIssueでご連絡させていただきます。

## その他連絡事項

上記コメントの中に添付されていたアニメーションGif に関しまして、[WCAG 達成基準 2.2.2 一時停止、停止、非表示](https://waic.jp/translations/WCAG22/#pause-stop-hide) に基づき削除させていただきました。ご了承ください。

**Comment by BoxPistols** [comment]
@johnykei 

ご確認ありがとうございます。主題の内容、承知いたしました。
また、閃光/点滅のあるGifの添付失礼いたしました。

引き続き、よろしくお願いいたします。

**Comment by johnykei** [comment]
@BoxPistols 

こちらのIssueで報告いただいた以下の件について修正対応が完了いたしました。
お時間がある時にでもご確認いただけると幸いです。

- ScrollToTopButtonコンポーネントのルートの要素を `a` から `button` 要素を使うように変更
- デフォルトの `aria-label` を「ページの先頭へ戻る」に変更

このIssueはこちらでクローズさせていただきます。もし、何か問題がありましたらまたコメントしてください。

改めて、ありがとうございました。

**Comment by BoxPistols** [comment]
@johnykei 

上記の件、確認しました。
ご提案お聞きいただき、ありがとうございました！

- https://github.com/digital-go-jp/design-system-example-components/pull/28/commits/06debcc0f85ed2fd9e9702d9ac6051447131dd49
