### ISSUE TITLE
PullRequestテンプレートの作成

### ISSUE THREAD

**Issue by sacky3105** [digital-go-jp/design-system-example-components#6]
PullRequestテンプレートがあった方がプルリクエストが送りやすくなると思うので、PullRequestテンプレート作成したいです。

**Comment by johnykei** [comment]
@sacky3105 様

IssueおよびPRの作成ありがとうございます。

IssueテンプレートおよびPRテンプレートは現在調整中でございます。
また、当リポジトリではまずはコンポーネントそのものに関してのIssueを受け付けたいと考えております。

作成していただいたPRに関してはテンプレート作成の参考にさせていただきます。

先程READMEの更新をし、方針について記載しましたので、大変申し訳ございませんが改めて内容をご確認の上、
お気づきの点やご要望がございましたらご連絡ください。

何卒よろしくお願いいたします。

**Comment by johnykei** [comment]
上記のコメントの通り、申し訳ございませんがクローズさせていただきます。
ありがとうございました。
