### ISSUE TITLE
Storybook の自動デプロイ

### ISSUE THREAD

**Issue by morinokami** [digital-go-jp/design-system-example-components#8]
Storybook によるコンポーネントの動作確認について、現状ローカルで各自コマンドを実行しておこなうようになっていますが、たとえば https://storybook.js.org/docs/sharing/publish-storybook#github-pages にあるように、CI/CD を通じて GitHub Pages などに自動デプロイされるようにしてその URL を README に書いておくと、ブラウザのみで完結するため色々な人が確認しやすくなり良いと思うのですが、どうでしょうか？

**Comment by johnykei** [comment]
@morinokami 様

Issueの作成ありがとうございます。
Storybookについてですが、外部向けの公開は現在調整中です。
少しお時間を頂きますが、お待ちいただければと思います。

また、当リポジトリではまずはコンポーネントそのものに関してのIssueを受け付けたいと考えております。

先程READMEの更新をし、方針について記載しましたので、大変申し訳ございませんが改めて内容をご確認の上、
お気づきの点やご要望がございましたらご連絡ください。
